package packt.java.spring.mvc.dreamcar.pojo;

// Generated Nov 26, 2018 11:56:04 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auction generated by hbm2java
 */
@Entity
@Table(name = "auction", catalog = "dreamcar_reverse_auction")
public class Auction implements java.io.Serializable {

	private Integer auctionId;
	private User userByWinnerId;
	private Component component;
	private User userByOwnerId;
	private String currencyType;
	private float targetPrice;
	private Date startDate;
	private Date endDate;
	private int quantity;
	private int statusId;
	private Set<Bid> bids = new HashSet<Bid>(0);

	public Auction() {
	}

	public Auction(Component component, User userByOwnerId,
			String currencyType, float targetPrice, Date startDate,
			Date endDate, int quantity, int statusId) {
		this.component = component;
		this.userByOwnerId = userByOwnerId;
		this.currencyType = currencyType;
		this.targetPrice = targetPrice;
		this.startDate = startDate;
		this.endDate = endDate;
		this.quantity = quantity;
		this.statusId = statusId;
	}

	public Auction(User userByWinnerId, Component component,
			User userByOwnerId, String currencyType, float targetPrice,
			Date startDate, Date endDate, int quantity, int statusId,
			Set<Bid> bids) {
		this.userByWinnerId = userByWinnerId;
		this.component = component;
		this.userByOwnerId = userByOwnerId;
		this.currencyType = currencyType;
		this.targetPrice = targetPrice;
		this.startDate = startDate;
		this.endDate = endDate;
		this.quantity = quantity;
		this.statusId = statusId;
		this.bids = bids;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "auctionId", unique = true, nullable = false)
	public Integer getAuctionId() {
		return this.auctionId;
	}

	public void setAuctionId(Integer auctionId) {
		this.auctionId = auctionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "winnerId")
	public User getUserByWinnerId() {
		return this.userByWinnerId;
	}

	public void setUserByWinnerId(User userByWinnerId) {
		this.userByWinnerId = userByWinnerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componentId", nullable = false)
	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ownerId", nullable = false)
	public User getUserByOwnerId() {
		return this.userByOwnerId;
	}

	public void setUserByOwnerId(User userByOwnerId) {
		this.userByOwnerId = userByOwnerId;
	}

	@Column(name = "currencyType", nullable = false, length = 10)
	public String getCurrencyType() {
		return this.currencyType;
	}

	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType;
	}

	@Column(name = "targetPrice", nullable = false, precision = 12, scale = 0)
	public float getTargetPrice() {
		return this.targetPrice;
	}

	public void setTargetPrice(float targetPrice) {
		this.targetPrice = targetPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startDate", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endDate", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "statusId", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auction")
	public Set<Bid> getBids() {
		return this.bids;
	}

	public void setBids(Set<Bid> bids) {
		this.bids = bids;
	}

}
